/*jshint esversion: 6 */
/**
 * Created by yen-chieh on 5/11/16.
 */

module.exports = {
	API_DOMAIN: "http://localhost:8080/",

	API_REMOVE_LIST: "removeFromList",
	API_USER_STOCK_LIST: "getUserStockList",
	API_SEARCH_STOCK: "getQuoteBySymbol",
	API_ADD_STOCK: "addToList",
	API_CHECK_USER: "checkUser",
	API_RETRIEVE_USER: "user/get/",
	API_CHECK_EMAIL: "user/check/",
	API_REGISTER_LOGIN_USER: "user/registerOrLogin",
	API_ADD_WATCH_LIST: 'watchList/add',
	API_GET_WATCH_LIST: 'watchList/getByEmail',

	API_JSON_HEADER: {
		'Accept': 'application/json',
		'Content-Type': 'application/json'
	},

	FETCH_DATA_FROM_SERVER: 'FETCH_DATA',
	RECEIVED_QUOTE_DATA_SEARCH: 'RECEIVED_QUOTE_DATA_FOR_SEARCH',
	RECEIVED_QUOTE_DATA_WATCH: 'RECEIVED_QUOTE_DATA_FOR_WATCH',
	REFRESH_QUOTE_DATA_SEARCH: 'REFRESH_QUOTE_DATA_SEARCH',
	UPDATE_CHECKED_LIST: 'UPDATE_CHECKED_LIST',
	REMOVE_QUOTE: 'REMOVE_QUOTE',
	GET_QUOTE: 'GET_QUOTE',
	CREATE_LIST: 'CREATE_LIST',

	CHECKED_USER_EXISTS: 'CHECKED_USER_EXISTS',
	RECEIVED_USER_DATA: 'RECEIVED_USER_DATA',
	ERROR_USER_REGISTER_LOGIN: 'ERROR_USER_REGISTER',
	USER_REGISTER_LOGIN_SUCCESS: 'USER_REGISTER_SUCCESS',

	WATCH_LIST_UPDATED: "WATCH_LIST_UPDATED",
	RECEIVED_WATCH_LIST: "RECEIVED_WATCH_LIST",


	LOCAL_WATCH_LIST: "Watch_List"
};
